redis:
  addr: "192.168.8.237:6379"
  user: ""
  password: ""
  db: 2

# mysql connect configuration
mysql:
  username: "root"
  password: "123456"
  path: "127.0.0.1:3306"
  db-name: 'qmPlus'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 10

zap:
  level: 'info'
  log-in-console: true
  path: './logs/app.log'
  max-size: 5   #文件分割的文件大小
  max-backups: 3   #保留日志文件个数
